from __future__ import annotations

import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

from math_tutor.prompt_catalog import PROMPTS_BY_SLUG
from math_tutor.site_cards import (
    document_label,
    format_assignment_display_name,
    match_assignments_to_record,
    record_page_filename,
    render_single_model_row_card,
)
from math_tutor.site_models import DocumentRecord, PromptOutputRecord


class SiteCardsTests(unittest.TestCase):
    def test_document_label_and_record_page_filename(self) -> None:
        record = DocumentRecord(
            file_id="4401267",
            display_name="Alg 2 Trig H Chp 5.1 Note.docx",
            pdf_path=None,
            download_url=None,
            fetched_at=None,
            prompt_outputs=[],
        )
        self.assertEqual(document_label(record), "Chapter 5.1")
        self.assertEqual(record_page_filename(record), "doc-4401267.html")

    def test_match_assignments_to_record(self) -> None:
        record = DocumentRecord(
            file_id="4506904",
            display_name="Alg 2 Trig H Chp 6.1 Note.docx",
            pdf_path=None,
            download_url=None,
            fetched_at=None,
            prompt_outputs=[],
        )
        assignments = [
            Path("4517747_chp-6-1-6-2-work.pdf"),
            Path("9999999_chp-7-1-work.pdf"),
        ]
        matched = match_assignments_to_record(assignments, record)
        self.assertEqual(matched, [Path("4517747_chp-6-1-6-2-work.pdf")])
        self.assertEqual(format_assignment_display_name(matched[0]), "Chp 6.1 6.2 Work")

    def test_render_single_model_row_card(self) -> None:
        with TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            html_path = root / "mm.html"
            pdf_path = root / "mm.pdf"
            html_path.write_text("<html></html>", encoding="utf-8")
            pdf_path.write_text("pdf", encoding="utf-8")

            html = render_single_model_row_card(
                title="Mental Math",
                specs=(PROMPTS_BY_SLUG["mental-math-gpt5"],),
                outputs_by_slug={
                    "mental-math-gpt5": PromptOutputRecord(
                        slug="mental-math-gpt5",
                        title="Mental Math (GPT-5.4)",
                        response_path=root / "mm.md",
                        response_html_path=html_path,
                        response_pdf_path=pdf_path,
                        metadata_path=None,
                        processed_at="2026-04-02T00:00:00Z",
                        response_markdown=None,
                    )
                },
                link_label="Mental Math",
                output_dir=root,
                site_dir=root,
                base_path="",
                build_site_href=lambda **_: "responses/mm.html",
                model_label_for_spec=lambda prompt_spec: prompt_spec.title,
            )
            self.assertIn("Mental Math", html)
            self.assertIn("responses/mm.html", html)
            self.assertIn("Generated by AI", html)


if __name__ == "__main__":
    unittest.main()
