from __future__ import annotations

import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

from math_tutor.prompt_catalog import PROMPTS_BY_SLUG
from math_tutor.site_cards import (
    document_label,
    document_title,
    format_assignment_display_name,
    match_assignments_to_record,
    record_page_filename,
    render_assignments_card_with_variant,
    render_single_model_row_card,
)
from math_tutor.site_models import DocumentRecord, PromptOutputRecord
from math_tutor.site_prompt_cards import build_document_prompt_card_groups


class SiteCardsTests(unittest.TestCase):
    def test_document_label_uses_curated_chapter_title_and_record_page_filename(self) -> None:
        record = DocumentRecord(
            file_id="4401267",
            display_name="Alg 2 Trig H Chp 5.1 Note.docx",
            pdf_path=None,
            download_url=None,
            fetched_at=None,
            prompt_outputs=[],
        )
        self.assertEqual(document_title(record), "Radians, Arc Length, and Sector Area")
        self.assertEqual(document_label(record), "Chapter 5.1: Radians, Arc Length, and Sector Area")
        self.assertEqual(record_page_filename(record), "doc-4401267.html")

    def test_document_title_prefers_generated_study_guide_title(self) -> None:
        record = DocumentRecord(
            file_id="4401267",
            display_name="Alg 2 Trig H Chp 5.1 Note.docx",
            pdf_path=None,
            download_url=None,
            fetched_at=None,
            prompt_outputs=[
                PromptOutputRecord(
                    slug="study-guide",
                    title="Study Guide",
                    response_path=Path("output/responses/example.md"),
                    response_html_path=None,
                    response_pdf_path=None,
                    metadata_path=None,
                    processed_at="2026-04-02T00:00:00Z",
                    response_markdown=(
                        "## Title\n"
                        "Angles as Rotation and Arc Measure\n\n"
                        "## Short Summary\n"
                        "This document introduces radians.\n"
                    ),
                )
            ],
        )
        self.assertEqual(document_title(record), "Angles as Rotation and Arc Measure")
        self.assertEqual(document_label(record), "Chapter 5.1: Angles as Rotation and Arc Measure")

    def test_match_assignments_to_record(self) -> None:
        record = DocumentRecord(
            file_id="4506904",
            display_name="Alg 2 Trig H Chp 6.1 Note.docx",
            pdf_path=None,
            download_url=None,
            fetched_at=None,
            prompt_outputs=[],
        )
        assignments = [
            Path("4517747_chp-6-1-6-2-work.pdf"),
            Path("9999999_chp-7-1-work.pdf"),
        ]
        matched = match_assignments_to_record(assignments, record)
        self.assertEqual(matched, [Path("4517747_chp-6-1-6-2-work.pdf")])
        self.assertEqual(format_assignment_display_name(matched[0]), "Chapter 6.1 6.2 Work")

    def test_render_single_model_row_card(self) -> None:
        with TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            html_path = root / "mm.html"
            pdf_path = root / "mm.pdf"
            html_path.write_text("<html></html>", encoding="utf-8")
            pdf_path.write_text("pdf", encoding="utf-8")

            html = render_single_model_row_card(
                title="Mental Math",
                specs=(PROMPTS_BY_SLUG["mental-math-gpt5"],),
                outputs_by_slug={
                    "mental-math-gpt5": PromptOutputRecord(
                        slug="mental-math-gpt5",
                        title="Mental Math (GPT-5.4)",
                        response_path=root / "mm.md",
                        response_html_path=html_path,
                        response_pdf_path=pdf_path,
                        metadata_path=None,
                        processed_at="2026-04-02T00:00:00Z",
                        response_markdown=None,
                    )
                },
                link_label="Mental Math",
                output_dir=root,
                site_dir=root,
                base_path="",
                build_site_href=lambda **_: "responses/mm.html",
                model_label_for_spec=lambda prompt_spec: prompt_spec.title,
            )
            self.assertIn("Mental Math", html)
            self.assertIn("responses/mm.html", html)
            self.assertIn("Generated by AI", html)

    def test_render_assignments_card_includes_assignment_grading_links_under_assignments(self) -> None:
        with TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            assignment_path = root / "4435419_chp-5-1-work.pdf"
            response_html_path = root / "4435419__auto-grading-assignment.html"
            response_pdf_path = root / "4435419__auto-grading-assignment.pdf"
            assignment_path.write_text("assignment", encoding="utf-8")
            response_html_path.write_text("<html></html>", encoding="utf-8")
            response_pdf_path.write_text("pdf", encoding="utf-8")

            html = render_assignments_card_with_variant(
                assignments=[assignment_path],
                site_dir=root / "site",
                base_path="/site/",
                assignment_prompt_outputs_by_filename={
                    assignment_path.name: [
                        PromptOutputRecord(
                            slug="auto-grading-assignment",
                            title="Auto Grading Assignment",
                            response_path=root / "4435419__auto-grading-assignment.md",
                            response_html_path=response_html_path,
                            response_pdf_path=response_pdf_path,
                            metadata_path=None,
                            processed_at="2026-04-03T00:00:00Z",
                            response_markdown=None,
                        )
                    ]
                },
            )

            self.assertIn("Open Assignment", html)
            self.assertIn("AI Grade", html)
            self.assertIn("/site/assignments/ai-grading/4435419__auto-grading-assignment.html", html)
            self.assertIn("/site/assignments/ai-grading/4435419__auto-grading-assignment.pdf", html)

    def test_build_document_prompt_card_groups_renames_study_guide_card_to_quick_reference(self) -> None:
        with TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            study_html_path = root / "study-guide.html"
            study_pdf_path = root / "study-guide.pdf"
            study_html_path.write_text("<html></html>", encoding="utf-8")
            study_pdf_path.write_text("pdf", encoding="utf-8")

            record = DocumentRecord(
                file_id="4401267",
                display_name="Alg 2 Trig H Chp 5.1 Note.docx",
                pdf_path=None,
                download_url=None,
                fetched_at=None,
                prompt_outputs=[
                    PromptOutputRecord(
                        slug="study-guide",
                        title="Study Guide",
                        response_path=root / "study-guide.md",
                        response_html_path=study_html_path,
                        response_pdf_path=study_pdf_path,
                        metadata_path=None,
                        processed_at="2026-04-08T00:00:00Z",
                        response_markdown=None,
                    )
                ],
            )

            groups = build_document_prompt_card_groups(
                record=record,
                output_dir=root,
                site_dir=root,
                base_path="/site/",
                experience_variant="default",
            )

            learn_html = "\n".join(groups["learn"])
            self.assertIn("Quick Reference", learn_html)
            self.assertNotIn(">Study Guide<", learn_html)


if __name__ == "__main__":
    unittest.main()
