"""Reusable site-card rendering helpers for document pages."""

from __future__ import annotations

import html
import shutil
from pathlib import Path
from typing import Callable

from math_tutor.chaptering import format_assignment_display_name, parse_assignment_chapters, parse_display_name_chapter
from math_tutor.prompt_catalog import DEFAULT_MODEL, PromptSpec
from math_tutor.response_artifacts import pretty_title
from math_tutor.site_models import DocumentRecord, PromptOutputRecord


def record_page_filename(record: DocumentRecord) -> str:
    return f"doc-{record.file_id}.html"


def document_label(record: DocumentRecord) -> str:
    chapter = parse_display_name_chapter(record.display_name)
    if chapter:
        return f"Chapter {chapter}"
    return pretty_title(record.display_name)


def load_assignment_files(output_dir: Path) -> list[Path]:
    assignments_dir = output_dir / "downloads" / "assignments"
    if not assignments_dir.exists():
        return []
    return sorted(assignments_dir.glob("*.pdf"))


def match_assignments_to_record(assignments: list[Path], record: DocumentRecord) -> list[Path]:
    record_chapter = parse_display_name_chapter(record.display_name)
    if not record_chapter:
        return []
    return sorted(
        (path for path in assignments if any(chapter in record_chapter for chapter in parse_assignment_chapters(path.name))),
        key=lambda path: path.name,
    )


def render_assignments_card(assignments: list[Path], site_dir: Path, base_path: str) -> str:
    if not assignments:
        return ""
    assignments_dir = site_dir / "assignments"
    assignments_dir.mkdir(parents=True, exist_ok=True)
    links: list[str] = []
    for source in assignments:
        destination = assignments_dir / source.name
        if not destination.exists() or source.stat().st_mtime_ns != destination.stat().st_mtime_ns:
            shutil.copy2(source, destination)
        href = f"{base_path}assignments/{source.name}" if base_path else f"assignments/{source.name}"
        links.append(f'<a href="{html.escape(href)}">{html.escape(format_assignment_display_name(source))}</a>')
    return f"""
      <section class="prompt-card">
        <h3>Assignments</h3>
        <div class="chip-row"><span class="chip chip-lock"><span class="auth-icon" aria-hidden="true">&#128737;&#65038;</span>Authorization Required</span></div>
        <div class="link-row">
          {' '.join(links)}
        </div>
      </section>
    """


def render_single_model_row_card(
    *,
    title: str,
    specs: tuple[PromptSpec, ...],
    outputs_by_slug: dict[str, PromptOutputRecord],
    link_label: str,
    output_dir: Path,
    site_dir: Path,
    base_path: str,
    build_site_href: Callable[..., str],
    model_label_for_spec: Callable[[PromptSpec], str],
    hide_model: bool = False,
) -> str:
    model_rows: list[str] = []

    for spec in specs:
        output = outputs_by_slug.get(spec.slug)
        if not output or not output.processed_at:
            continue
        parts: list[str] = []
        if output.response_html_path and output.response_html_path.exists():
            href = build_site_href(path=output.response_html_path, output_dir=output_dir, site_dir=site_dir, base_path=base_path)
            parts.append(f'<a href="{html.escape(href)}">{html.escape(link_label)}</a>')
        if spec.generate_response_pdf and output.response_pdf_path and output.response_pdf_path.exists():
            href = build_site_href(path=output.response_pdf_path, output_dir=output_dir, site_dir=site_dir, base_path=base_path)
            parts.append(f'<a href="{html.escape(href)}" class="pdf-link">PDF</a>')
        model_rows.append(f"""
      <div class="olympiad-model-row">
        {"" if hide_model else model_chip(spec, model_label_for_spec)}
        <div class="olympiad-links">
          {' '.join(parts)}
        </div>
      </div>""")

    if not model_rows:
        return ""

    return f"""
      <section class="prompt-card">
        <h3>{html.escape(title)}</h3>
        <div class="chip-row"><span class="chip chip-ai">Generated by AI</span></div>
        {''.join(model_rows)}
      </section>
    """


def render_inspiring_videos_card(
    *,
    specs: tuple[PromptSpec, ...],
    outputs_by_slug: dict[str, PromptOutputRecord],
    output_dir: Path,
    site_dir: Path,
    base_path: str,
    build_site_href: Callable[..., str],
    model_label_for_spec: Callable[[PromptSpec], str],
) -> str:
    return render_single_model_row_card(
        title="Inspiring Videos",
        specs=specs,
        outputs_by_slug=outputs_by_slug,
        link_label="Watch Picks",
        output_dir=output_dir,
        site_dir=site_dir,
        base_path=base_path,
        build_site_href=build_site_href,
        model_label_for_spec=model_label_for_spec,
    )


def render_olympiad_combined(
    *,
    problem_specs: tuple[PromptSpec, ...],
    solution_specs: tuple[PromptSpec, ...],
    outputs_by_slug: dict[str, PromptOutputRecord],
    output_dir: Path,
    site_dir: Path,
    base_path: str,
    build_site_href: Callable[..., str],
    model_label_for_spec: Callable[[PromptSpec], str],
) -> str:
    model_rows: list[str] = []

    for problem_spec, solution_spec in zip(problem_specs, solution_specs):
        problem_output = outputs_by_slug.get(problem_spec.slug)
        solution_output = outputs_by_slug.get(solution_spec.slug)
        has_data = (problem_output and problem_output.processed_at) or (solution_output and solution_output.processed_at)
        if not has_data:
            continue

        def inline_links(output: PromptOutputRecord | None, spec: PromptSpec, label: str) -> str:
            if not output:
                return ""
            parts: list[str] = []
            if output.response_html_path and output.response_html_path.exists():
                href = build_site_href(path=output.response_html_path, output_dir=output_dir, site_dir=site_dir, base_path=base_path)
                parts.append(f'<a href="{html.escape(href)}">{html.escape(label)}</a>')
            if spec.generate_response_pdf and output.response_pdf_path and output.response_pdf_path.exists():
                href = build_site_href(path=output.response_pdf_path, output_dir=output_dir, site_dir=site_dir, base_path=base_path)
                parts.append(f'<a href="{html.escape(href)}" class="pdf-link">PDF</a>')
            return " ".join(parts)

        items_html = "   ".join(part for part in [
            inline_links(problem_output, problem_spec, "Problems"),
            inline_links(solution_output, solution_spec, "Solutions"),
        ] if part)

        model_rows.append(f"""
      <div class="olympiad-model-row">
        {model_chip(problem_spec, model_label_for_spec)}
        <div class="olympiad-links">
          {items_html}
        </div>
      </div>""")

    if not model_rows:
        return ""

    return f"""
      <section class="prompt-card">
        <h3>Olympiad Problems &amp; Solutions</h3>
        <div class="chip-row"><span class="chip chip-ai">Generated by AI</span></div>
        {''.join(model_rows)}
      </section>
    """


def model_chip(prompt_spec: PromptSpec, model_label_for_spec: Callable[[PromptSpec], str]) -> str:
    label = model_label_for_spec(prompt_spec)
    model_name = prompt_spec.model or DEFAULT_MODEL
    if prompt_spec.model is None:
        css = "chip"
    elif model_name.startswith("gemini"):
        css = "chip chip-gemini"
    else:
        css = "chip chip-model"
    return f'<span class="{css}">{html.escape(label)}</span>'
